In [1]:
import torch

# 变换操作

## torch.repeat

In [6]:
a = torch.tensor([1, 2, 3, 1.1, 2.1, 3.1]).view(2, 3)
print(a)
print(a.repeat(1, 3))
print(a.repeat(3, 1))

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000, 1.0000, 2.0000, 3.0000, 1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000, 1.1000, 2.1000, 3.1000, 1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])


## torch.view

In [10]:
a = torch.tensor([1, 2, 3, 1.1, 2.1, 3.1]).view(2, 3)
print(a)
print(a.view(1, 6))
print(a.view(3, 2))
#先把原矩阵转为1维矩阵, 再view, 长宽长度变换

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000, 1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000],
        [3.0000, 1.1000],
        [2.1000, 3.1000]])


## torch.permute

In [14]:
#理解为沿着某一维度旋转操作的组合
a = torch.rand(2, 3, 3)
print(a)
print(a.permute(2, 0, 1))#c, h, w -->w, c, h
print(a.permute(0, 2, 1).permute(1,0, 2))
#上述两个操作等价, 即通道数不变, 长宽旋转, 再w不变, 通道与h平面旋转,理解为长方体也可以.

tensor([[[0.6398, 0.2360, 0.1091],
         [0.1882, 0.1385, 0.6174],
         [0.6457, 0.8207, 0.0792]],

        [[0.6341, 0.9761, 0.6546],
         [0.8318, 0.8928, 0.2427],
         [0.9904, 0.8188, 0.5234]]])
tensor([[[0.6398, 0.1882, 0.6457],
         [0.6341, 0.8318, 0.9904]],

        [[0.2360, 0.1385, 0.8207],
         [0.9761, 0.8928, 0.8188]],

        [[0.1091, 0.6174, 0.0792],
         [0.6546, 0.2427, 0.5234]]])
tensor([[[0.6398, 0.1882, 0.6457],
         [0.6341, 0.8318, 0.9904]],

        [[0.2360, 0.1385, 0.8207],
         [0.9761, 0.8928, 0.8188]],

        [[0.1091, 0.6174, 0.0792],
         [0.6546, 0.2427, 0.5234]]])


# None

In [11]:
import torch
a = torch.rand(2, 3)
print(a)
print(a[None].shape) #相当于在dim = 0加一维
print(a[:, None, :]) #相当于在dim=1增加一维空白维度, 可以配合expand使用
print(a[:, None, :].shape)

tensor([[0.8063, 0.8291, 0.0403],
        [0.0591, 0.5231, 0.9671]])
torch.Size([1, 2, 3])
tensor([[[0.8063, 0.8291, 0.0403]],

        [[0.0591, 0.5231, 0.9671]]])
torch.Size([2, 1, 3])


# repeat 和 expand

repeat为在某一维度重复的次数

expand为某一维度扩展到->某个值

In [15]:
import torch
a = torch.rand(2, 3)
print(a)
print(a[None]) #相当于在dim = 0加一维
print(a[None].expand(2, 2, 3)) #相当于在dim = 0加一维
print('\n'+'#'*20 + '\n')
print(a[:, None, :]) 
print(a[:, None, :].expand(2, 2, 3)) #相当于在dim=1增加一维空白维度, 可以配合expand使用



tensor([[0.7718, 0.2674, 0.8378],
        [0.8361, 0.4883, 0.9315]])
tensor([[[0.7718, 0.2674, 0.8378],
         [0.8361, 0.4883, 0.9315]]])
tensor([[[0.7718, 0.2674, 0.8378],
         [0.8361, 0.4883, 0.9315]],

        [[0.7718, 0.2674, 0.8378],
         [0.8361, 0.4883, 0.9315]]])

####################

tensor([[[0.7718, 0.2674, 0.8378]],

        [[0.8361, 0.4883, 0.9315]]])
tensor([[[0.7718, 0.2674, 0.8378],
         [0.7718, 0.2674, 0.8378]],

        [[0.8361, 0.4883, 0.9315],
         [0.8361, 0.4883, 0.9315]]])


# :与...

In [ ]:
多维数组, 索引严格按照位置., 如三维, a[:, 2]等价于a[:, 2, :]!=a[..., 2]

In [25]:
import torch

a = torch.rand(2, 3, 4)
print(a)
print(a[:, 2])
print(a[:, 2, :])  
print(a[..., 2])
print('\n'+'#'*20 + '\n')
b = torch.rand(2, 4)
print(b)
print(b[:, 2])
print(b[..., 2])

tensor([[[0.2054, 0.5011, 0.0172, 0.0823],
         [0.5334, 0.1181, 0.1707, 0.3074],
         [0.8150, 0.9895, 0.6376, 0.8298]],

        [[0.0887, 0.7321, 0.5029, 0.3481],
         [0.1371, 0.9003, 0.9134, 0.2163],
         [0.7767, 0.0965, 0.6920, 0.8783]]])
tensor([[0.8150, 0.9895, 0.6376, 0.8298],
        [0.7767, 0.0965, 0.6920, 0.8783]])
tensor([[0.8150, 0.9895, 0.6376, 0.8298],
        [0.7767, 0.0965, 0.6920, 0.8783]])
tensor([[0.0172, 0.1707, 0.6376],
        [0.5029, 0.9134, 0.6920]])

####################

tensor([[0.1151, 0.5351, 0.2433, 0.6230],
        [0.5952, 0.7412, 0.3889, 0.4852]])
tensor([0.2433, 0.3889])
tensor([0.2433, 0.3889])


# torch.where

In [27]:
import torch
a = torch.randn(2, 4)
print(a)
torch.where(a>0.2, torch.tensor([1]), torch.tensor([0])) # ? yes no, 

tensor([[ 1.6762, -0.6629, -0.7343, -0.1085],
        [ 0.8326, -1.4595, -0.4163,  0.9151]])


tensor([[1, 0, 0, 0],
        [1, 0, 0, 1]])

# torch.min与torch.max

In [31]:
import torch
a = torch.randn(2, 4)
print(a)
a.min(-1)

tensor([[ 3.3850e+00,  1.5893e-01,  1.6896e+00, -1.3328e-01],
        [-5.9827e-04,  3.2300e-01,  1.1232e+00,  6.3458e-01]])


torch.return_types.min(
values=tensor([-0.1333, -0.0006]),
indices=tensor([3, 0]))

In [1]:
a = [1, 2, 3, 4, 5, 6]
b = a[:2] + a[4:6]
b

[1, 2, 5, 6]

# detach