In [1]:
import torch

# 变换操作

## torch.repeat

In [6]:
a = torch.tensor([1, 2, 3, 1.1, 2.1, 3.1]).view(2, 3)
print(a)
print(a.repeat(1, 3))
print(a.repeat(3, 1))

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000, 1.0000, 2.0000, 3.0000, 1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000, 1.1000, 2.1000, 3.1000, 1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000],
        [1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])


## torch.view

In [10]:
a = torch.tensor([1, 2, 3, 1.1, 2.1, 3.1]).view(2, 3)
print(a)
print(a.view(1, 6))
print(a.view(3, 2))
#先把原矩阵转为1维矩阵, 再view, 长宽长度变换

tensor([[1.0000, 2.0000, 3.0000],
        [1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000, 3.0000, 1.1000, 2.1000, 3.1000]])
tensor([[1.0000, 2.0000],
        [3.0000, 1.1000],
        [2.1000, 3.1000]])


## torch.permute

In [14]:
a = torch.rand(2, 3, 3)
print(a)
print(a.permute(2, 0, 1))#c, h, w -->w, c, h
print(a.permute(0, 2, 1).permute(1,0, 2))
#上述两个操作等价, 即通道数不变, 长宽旋转, 再w不变, 通道与h平面旋转,理解为长方体也可以.

tensor([[[0.6398, 0.2360, 0.1091],
         [0.1882, 0.1385, 0.6174],
         [0.6457, 0.8207, 0.0792]],

        [[0.6341, 0.9761, 0.6546],
         [0.8318, 0.8928, 0.2427],
         [0.9904, 0.8188, 0.5234]]])
tensor([[[0.6398, 0.1882, 0.6457],
         [0.6341, 0.8318, 0.9904]],

        [[0.2360, 0.1385, 0.8207],
         [0.9761, 0.8928, 0.8188]],

        [[0.1091, 0.6174, 0.0792],
         [0.6546, 0.2427, 0.5234]]])
tensor([[[0.6398, 0.1882, 0.6457],
         [0.6341, 0.8318, 0.9904]],

        [[0.2360, 0.1385, 0.8207],
         [0.9761, 0.8928, 0.8188]],

        [[0.1091, 0.6174, 0.0792],
         [0.6546, 0.2427, 0.5234]]])
