# 切片

In [20]:
#1. :, 与...等价.
#2. ::: start, stop, step
#3. 注意a[:1], 与a[:, 1]区别
#4. a[2], a[2, :]
import numpy as np

a = np.arange(12).reshape(3, 4)
print(a)
print(a[1:])
print(a[1, :])
print(a[1, ...])
print(a[:1])
print(a[:, 1])
print(a[..., 1])
print(a[:, 1:])
print(a[..., 1:])
print('#'*50)
print(a[a>5])
print(a[2], a[2, :])

        

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 4  5  6  7]
 [ 8  9 10 11]]
[4 5 6 7]
[4 5 6 7]
[[0 1 2 3]]
[1 5 9]
[1 5 9]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
##################################################
[ 6  7  8  9 10 11]
[ 8  9 10 11] [ 8  9 10 11]


In [2]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])